rule set_config_from_profile:
    output:
        "current_config.txt"
    shell:
        "echo {config[current_config]} > {output}"

rule download_annotations:
    input:
        f"{workflow.basedir}/scripts/1-gisela_dl_annotations_and_images.py"
    output:  #output dir should be configurable and sent to script
        images=directory(f"dl/{config['current_config']}/images/"),
        annotations=directory(f"dl/{config['current_config']}/annotations/")
    conda:
        f"{workflow.basedir}/envs/webknossos.yml"
    script:
        f"{input}"

rule create_vector_files_yolo:
    input:
        annotations=rules.download_annotations.output.annotations
    output:  #output dir should be configurable and sent to script
        vectors=directory("dl/vectors/")
    conda:
        f"{workflow.basedir}/envs/webknossos.yml"
    script:
        f"{workflow.basedir}/scripts/2-create_yolov8_vectors_from_annotations.py"

rule create_yolo_dataset:
    input:
        rules.create_vector_files_yolo.output.vectors
    output:  #output dir should be configurable and sent to script
        dataset=directory("datasets")
    conda:
        f"{workflow.basedir}/envs/webknossos.yml"
    script:
        f"{workflow.basedir}/scripts/3-gisela_create_yolo_dataset.py"

#this rule needs fixing!!!
rule dl_test_images:
    input:
        f"{workflow.basedir}/scripts/4-dl_test_images_for_yolo.py"
    output:
        directory("dl/test_data")
    conda:
        f"{workflow.basedir}/envs/webknossos.yml"
    script:
        f"{input}"

rule yolo_train_py:
    input: 
        rules.create_yolo_dataset.output.dataset
    output:
        model=f"{os.getcwd()}/latest_model.pt"
    conda:
        f"{workflow.basedir}/envs/yolov8.yml"
    script:
        f"{workflow.basedir}/scripts/train_yolo_model.py"


rule yolo_train:
    input:
        rules.create_yolo_dataset.output.dataset
    conda:
        f"{workflow.basedir}/envs/yolov8.yml"
    shell:
        f"yolo segment train data={os.getcwd()}/datasets/dataset.yaml epochs=50 imgsz=512"
    

rule yolo_segment:
    input: 
        rules.yolo_train_py.output.model
    conda:
        f"{workflow.basedir}/envs/yolov8.yml"
    script:
        f"{workflow.basedir}/scripts/segment_large_image_using_yolo.py"

rule all:
    input:
        rules.create_yolo_dataset.output.dataset



# rule hello:
#     output: 'output.txt'
#     shell:
#         'echo hello world > {output}'
